---

- name: Install cloudwatch agent
  ansible.builtin.dnf:
    name: amazon-cloudwatch-agent
    state: present

- name: Copy cloudwatch agent config
  ansible.builtin.copy:
    src: files/amazon-cloudwatch-agent.json
    dest: /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    owner: root
    group: root
    mode: "0644"
